<?php

namespace Database\Seeders;

use App\Models\Tema;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MusicaSeeder2 extends Seeder
{
    public function run(): void
    {
        $entradaId   = Tema::where('slug', 'entrada')->first()?->id;
        $perdaoId    = Tema::where('slug', 'ato-penitencial')->first()?->id;
        $gloriaId    = Tema::where('slug', 'gloria')->first()?->id;
        $meditacaoId = Tema::where('slug', 'meditacao')->first()?->id;
        $aclamacaoId = Tema::where('slug', 'aclamacao-ao-evangelho')->first()?->id;
        $creioId     = Tema::where('slug', 'creio')->first()?->id;
        $ofertorioId = Tema::where('slug', 'ofertorio')->first()?->id;
        $comunhaoId  = Tema::where('slug', 'comunhao')->first()?->id;
        $finalId     = Tema::where('slug', 'final')->first()?->id;
        $louvorId    = Tema::where('slug', 'louvor')->first()?->id;
        $adoracaoId  = Tema::where('slug', 'adoracao')->first()?->id;
        $entregaId   = Tema::where('slug', 'entrega')->first()?->id;
        $espiritoId  = Tema::where('slug', 'espirito-santo')->first()?->id;
        $mariaId     = Tema::where('slug', 'maria')->first()?->id;

        $musicas = [
            [
                'numero'  => 4,
                'titulo'  => 'Aleluia, Glória ao Senhor',
                'letra'   => "**Aleluia, Aleluia, Aleluia, Aleluia, Glória ao Senhor!**\nAleluia, Aleluia, Aleluia, Aleluia, Glória ao Senhor! (bis)\nGlória ao Senhor Nosso Pai (3x) Glória ao Senhor!\nGlória a Jesus Cristo Redentor (3x) Glória ao Senhor!\nGlória ao Espírito Santo (3x) Glória ao Senhor!\nGlória à Santíssima Trindade (3x) Glória ao Senhor!",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 10,
                'titulo'  => 'A Melhor Oração é Amar',
                'letra'   => "**A melhor oração é amar (2x)**\nSe não sabes amar, tu não deves orar, a melhor oração é amar.\nQuem irá ensinar a melhor oração, a melhor oração é amar.\nÉ Jesus quem ensina a melhor oração, a melhor oração é amar.\nO maior Mandamento é o amor, diz Jesus, a melhor oração é amar.\nSe amares o inimigo, cumprirás lei do amor, a melhor oração é amar.\nÉs bem aventurado se amas o inimigo, a melhor oração é amar.\nSe as tristezas fizerem doer o teu coração, a melhor oração é amar.\nMesmo nas lágrimas, conhecemos a grande oração, a melhor oração é amar.",
                'autor'   => 'Desconhecido',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 12,
                'titulo'  => 'Alegres Vamos à Casa do Pai',
                'letra'   => "**Alegres vamos à casa do Pai e na alegria cantar Seu louvor,**\n**Em Sua casa, somos felizes, participamos da ceia do amor!**\n1. A alegria nos vem do Senhor, Seu amor nos conduz pela paz.\nEle é Luz que ilumina Seu povo, segurança lhe dá e salvação.\n2. O Senhor nos concede Seus bens, nos convida à Sua mesa sentar;\nE partilha conosco Seu pão, somos irmãos ao redor deste altar.\n3. Voltarei sempre à casa do Pai, do meu Deus cantarei o louvor,\nSerei bem feliz uma vida que busque a Deus como fonte de amor.",
                'autor'   => 'Desconhecido',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 13,
                'titulo'  => 'Aleluia, Aleluia, Aleluia, Aleluia',
                'letra'   => "Rendei graças ao Senhor: *que seu amor é sem fim.*\nDigam o povo do Senhor: *que seu amor é sem fim.*\nDigam os seus sacerdotes: *que seu amor é sem fim.*\nSua destra fez prodígios, pois o Senhor nos salvou.\nVivere, não morrerei: *para Seu amor proclamar.*\nConstrutores me rejeitaram, mas o Senhor me escolheu.\nFez-me a pedra principal, pois o Senhor me escolheu.\nRendei graças ao Senhor: *que seu amor é sem fim.*\nDigam todos os cristãos: *que seu amor é sem fim.*\nDigam todos os remidos: *o seu amor é sem fim!*",
                'autor'   => 'Pe. Silvio Milanez',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 14,
                'titulo'  => 'A Nós Descei, Divina Luz',
                'letra'   => "**A nós descei, Divina Luz (bis)**\n**A nós descei, Divina Luz, em nossas almas acendei o amor, o amor de Jesus. (bis)**\n1. Vós sois a alma da Igreja, vós sois a vida, sois o Amor;\nVós sois a graça benfazeja que nos irmana no Senhor.\n2. Divino Espírito descei. Os corações vinde inflamar,\nE as nossas almas preparar para o que Deus nos quer falar. (bis)",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $espiritoId,
                'ativo'   => true,
            ],
            [
                'numero'  => 18,
                'titulo'  => 'A Nós Descei, Divina Luz',
                'letra'   => "**A nós descei, Divina Luz, a nós descei Divina Luz**\n**em nossas almas acendei, o amor, o amor de Jesus (2x)**\n1. Vinde, Santo Espírito, o céu mandai da Tua luz um raio!\nVinde, Pai dos pobres, doador dos dons, luz dos corações\nConsolador, hospede de nossas almas, doce alívio, doce unção!\n2. Na fadiga, repouso, no ardor, brandura, e na dor coragem!\nVós sois repouso duradouro, brisa no calor! Consolador dos corações!\n3. Dobrai a dureza, aquecei o frio, livrai do desvio!\nAo acordar cada dia, dai vossa alegria eterna alegria!",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 19,
                'titulo'  => 'O Senhor Me Chamou a Trabalhar',
                'letra'   => "1. O Senhor me chamou a trabalhar. A messe é grande a ceifar\nDom de amor é a vida entregar, falou Jesus e assim o fez.\n**Está na hora, Senhor me chamou. Senhor, aqui estou!**\n2. Dom de amor é vida entregar, chegou a minha vez.\nEsta seara, no sertão em paz, Esta flor e o pássaro feliz que vês,\nno santuário, não poderão jamais viver esta vida singular que Deus nos dá.\nE minha alma cheia do amor de Deus, Palpitando a mesma vida divinal.\nMeu segredo do infinito Ser, ao chegar diante do Senhor, vou agradecer por esta vida eterna, fechando o dia na Fé.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 20,
                'titulo'  => 'A Minh\'Alma Tem Sede de Deus',
                'letra'   => "**A minh'alma tem sede de Deus, pelo Deus vivo anseia com ardor:**\n**Quando irei ao encontro de Deus, e verei Tua face, Senhor! (2x)**\n1. A ovelha sedenta procura o riacho, a minh'alma suspira por Deus. Onde O acho?...\n2. Pelas águas que correm suspira a ovelha, pelas fontes de Deus a minh'alma anseia.\n3. Dor e lágrimas são meu constante alimento.\nOnde está o teu Deus? Dizem os maus e aguento.\n4. Por que estás abatida e confusa, ó minh'alma?\nDeus é teu companheiro, espera e te acalma.",
                'autor'   => 'Reginaldo Veloso',
                'tom'     => 'D',
                'tema_id' => $meditacaoId,
                'ativo'   => true,
            ],
            [
                'numero'  => 24,
                'titulo'  => 'Se Jesus Te Satisfaz',
                'letra'   => "Se Jesus te satisfaz, bata palma (2x)\nCada um no seu cantinho aperte a mão do seu vizinho e cante bem baixinho bata palma.\nBate palma, outra vez. Se Jesus te satisfaz, bate palma.\nSe Jesus te satisfaz, bata palma, levante a mão, se já tem no Cristo fé, fique de pé.\nVamos todos nos sentar e um sorriso vamos dar, e cantar bem baixinho: bate palma.\nBate palma, outra vez. Se Jesus te satisfaz, bate palma...",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 28,
                'titulo'  => 'Bendigamos ao Senhor',
                'letra'   => "Bendigamos ao Senhor (2x) desde agora e para sempre bendigamos ao Senhor.",
                'autor'   => 'Desconhecido',
                'tom'     => 'D',
                'tema_id' => $louvorId,
                'ativo'   => true,
            ],
            [
                'numero'  => 31,
                'titulo'  => 'Cantai ao Senhor',
                'letra'   => "**Cantai ao Senhor um canto novo, aleluia! Pois Ele fez maravilhas, aleluia!**\n1. Cantai ao Senhor um canto novo, pois Ele fez maravilhas; a vitória provém de Sua mão e de Seu braço divino.\n2. O Senhor manifestou a salvação, aos pagãos revelou Sua justiça; não esqueceu Sua bondade o Seu amor pela casa de Israel.\n3. Os confins do universo, contemplaram a salvação do nosso Deus; aclamai ao Senhor, terra inteira, alegrai-vos e cantai!\n4. Cantai salmos ao Senhor ao som da harpa, ao som dos instrumentos, ao som dos clarins e dos cornetas ao Senhor, nosso Rei!\n5. Reboa a plenitude do oceano, o mundo e toda a gente, batam palmas os rios e as montanhas, exultem de alegria.\n6. Na presença do Senhor, pois Ele vem governar toda a terra, regerá o universo com justiça e as nações com equidade.\n7. Glória ao Pai, ao Filho e ao Santo Espírito, desde agora e para sempre, Ao Deus que é, que era e que vem, pelos séculos. Amém.",
                'autor'   => 'Gelineau',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 32,
                'titulo'  => 'Creio, Senhor',
                'letra'   => "**Creio, Senhor, mas aumenta minha fé!**\n1. Eu creio em Deus, Pai onipotente, Criador da terra e céu.\n2. Creio em Jesus, Jesus verdadeiro, verdadeiro homem, Deus.\n3. Creio no Espírito de Amor, grande dom que a Igreja recebeu.",
                'autor'   => 'Dom Navarro',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 33,
                'titulo'  => 'Vós Sois o Caminho',
                'letra'   => "**Vós sois o Caminho, a Verdade e a Vida, o Pão da alegria descido do céu!**\n1. Nós somos caminhantes, que marcham para os céus.\nVós sois o Caminho que nos conduz a Deus.\n2. Da noite da mentira, das trevas para a luz\nBusquemos a verdade, a verdade é só Jesus.\n3. Pecar é não ter vida, pecar é não ter luz,\nO caminho é verdade, seguir os passos de Jesus.\n4. Jesus, verdade e vida, caminho que conduz\nAs almas peregrinas que marcham para a luz.",
                'autor'   => 'Pe. Vigne',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 34,
                'titulo'  => 'Com Amor Eterno',
                'letra'   => "**Com amor eterno eu te amei; dei a minha vida por amor:**\n**\"Agora vai, também ama o teu irmão\"**\n1. Já não somos servos, mas os teus amigos:\nA Tua mesa nos sentamos pra comermos deste Pão.\n2. Que nossa amizade se estenda a todos,\nPois o Cristo nos ensina que o amor é dom total.\n3. Terá recompensa até um copo d'água.\nO amor é verdadeiro se traduz em gesto e vida.\n4. Cristo, partilhando sua graça e vida,\nQuer a unidade dos irmãos e vivamos também entre os irmãos.\n5. Que perseveremos no amor de Cristo,\nO vivermos sua amizade nos fortalece e alegria.\n6. O pão da alegria nos alimentou;\nQue de seja nossa força e nos sustente a caminhada.",
                'autor'   => 'Ir. Míria T. Kolling',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 35,
                'titulo'  => 'Contente Estou',
                'letra'   => "Contente estou, em meu coração: ao céu eu vou, esta é a minha canção.\nGlória e aleluia, ao céu eu vou, esta é minha canção.\n**Canção (2x) canção de amor, louvando sempre o Salvador!**\nEu louvarei a Cristo Rei, pois minha vida a Ele eu dei.\nEle deu paz ao coração, deu-me a certeza da Salvação!\nQuem dá a paz é só Jesus, Ele é a Deus vivo que nos conduz.",
                'autor'   => 'Nicoletti',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 36,
                'titulo'  => 'Com Alegria Ofereço',
                'letra'   => "**Com alegria ofereço o meu sacrifício e vou cantando e louvando ao Senhor!**\nÉ nossa força, és nossa vida, é por isso queremos louvar-Te\nAté Teu Nome elevar nossas mãos.\nO Teu poder que Te procura, caminhando à luz de Teu rosto\nÉ buscando a verdade e o amor.",
                'autor'   => 'Ir. Míria T. Kolling',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 37,
                'titulo'  => 'Deus Te Ama',
                'letra'   => "Deus te ama e te ama, assim devemos viver.\n**Deus é amor e te ama, assim devemos viver.**",
                'autor'   => 'Desconhecido',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 39,
                'titulo'  => 'Dia e Noite',
                'letra'   => "**Dia e noite, vai Teu Espírito, Senhor, comigo.**\n1. Se anoitece em meu caminho, vai teu Espírito, Senhor, comigo.\nNo descanso ou no cansaço, vai Teu Espírito, Senhor, comigo.\n2. Quando o sol vai se apagando, vai teu Espírito, Senhor, comigo.\nSe a mente agita, vai Teu Espírito, Senhor, comigo.\n3. Ao chegar a minha hora de vencer, vai teu Espírito, Senhor, comigo.\nVai levar-me perto de Ti, sei que estás junto a mim.",
                'autor'   => 'Pe. José Weber',
                'tom'     => 'D',
                'tema_id' => $finalId,
                'ativo'   => true,
            ],
            [
                'numero'  => 42,
                'titulo'  => 'É Impossível',
                'letra'   => "Olho em tudo e sempre encontro a ti. Estás no céu, na terra, onde for.\nJá não posso mais deixar de crer no teu amor.\n**É impossível não crer em Ti. É impossível não Te encontrar.**\n**É impossível não fazer de Ti meu ideal.**",
                'autor'   => 'Mª Eliza de Andrade Mendes',
                'tom'     => 'D',
                'tema_id' => $meditacaoId,
                'ativo'   => true,
            ],
            [
                'numero'  => 45,
                'titulo'  => 'Ele Tem o Mundo em Suas Mãos',
                'letra'   => "**Ele tem o mundo em suas mãos (bis)**\nEle é meu Deus e nosso Deus. Ele é meu Pai e nosso Pai.\n1. Ele fez o universo (2x)\n2. Ele é quem me deu a vida (2x)\n3. Ele amou a humanidade (2x)\n4. Ele deu Seu próprio Filho (2x)\n5. Me adotou por filho (2x)",
                'autor'   => 'Pe. Zezinho',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 46,
                'titulo'  => 'Envia Teu Espírito, Senhor',
                'letra'   => "**Envia teu Espírito, Senhor, e renova a face da terra (bis)**\n1. Bendize minha alma ao Senhor, Senhor, meu Deus, como és tão grande.\n2. Como são numerosas as tuas obras, Senhor. A terra está cheia das tuas criaturas.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $espiritoId,
                'ativo'   => true,
            ],
            [
                'numero'  => 47,
                'titulo'  => 'Eu Canto a Alegria, Senhor',
                'letra'   => "**Eu canto a alegria, Senhor, de ser perdoado no amor! (bis)**\nSenhor, tende piedade de nós!\nCristo, tende piedade de nós!\nSenhor, tende piedade de nós!",
                'autor'   => 'Pe. José Weber',
                'tom'     => 'D',
                'tema_id' => $perdaoId,
                'ativo'   => true,
            ],
            [
                'numero'  => 48,
                'titulo'  => 'Eu Cantarei',
                'letra'   => "**Eu cantarei (2x) Sempre ao Senhor (2x)**\n**Aleluia (2x) És, ó Cristo nossa vida, és, ó Cristo, nossa Luz!**\nTu és a Luz... Tu és o Pão... Tu és a paz...",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 50,
                'titulo'  => 'Eis o Pão da Vida',
                'letra'   => "**Eis o Pão da vida, eis o Pão dos céus\nQue alimenta o homem em marcha para Deus.**\n1. Um grande convite o Senhor nos fez e a Igreja o repete a toda vez.\n2. Feliz quem ouve e alegre vem, trazendo consigo o amor que tem.",
                'autor'   => 'J. R. Galvão',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 52,
                'titulo'  => 'Eu Confio em Nosso Senhor',
                'letra'   => "**Eu confio em Nosso Senhor com fé, esperança e amor (2x)**\n1. Creio em Deus, uno, trino e eterno, que criou o céu, a terra e o mar.\n2. Sou católico, crente e sincero, a meu Deus aprendi a adorar.\n3. Eu espero salvar a minha alma, com o auxílio da graça de Deus.",
                'autor'   => 'Jorge Pinheiro',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 53,
                'titulo'  => 'Faça Silêncio',
                'letra'   => "**Faça silêncio em seu coração, porque o Senhor lhe quer falar (bis)**\n1. Ele fala no silêncio total, no deserto de um coração que crê.\n2. Consolo em nossa dor.\n3. Ele fala na notícia do jornal, no gritando programa da TV.\n4. E aponta a Lei do Amor.",
                'autor'   => 'Zanata',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 54,
                'titulo'  => 'Eu Vim Para Que Todos Tenham Vida',
                'letra'   => "\"Eu vim para que todos tenham vida,\nque todos tenham vida plenamente!\"\n1. Reconstrói a tua vida em comunhão com teu Senhor.\n2. Onde está o teu irmão, Eu estou presente nele.\n3. Quem comer do Pão da Vida viverá eternamente.",
                'autor'   => 'Pe. José Weber',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 58,
                'titulo'  => 'Glória a Deus na Imensidão',
                'letra'   => "Senhor, Deus Pai Criador onipotente,\nNós vos louvamos e vos bendizemos!\nSenhor, Jesus, Ungênito do Pai,\nNós vos damos graças por toda a imensidão!\nSenhor, Espírito Santo, nós vos adoramos.\nGlória ao Pai, ao Filho e ao Espírito Santo!\nAgora e para sempre, por toda a eternidade.",
                'autor'   => 'Pe. Zezinho',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 61,
                'titulo'  => 'Glória, Glória, Aleluia',
                'letra'   => "**Glória, glória, aleluia (3x) louvemos ao Senhor!**\n1. Na beleza do que vemos, Deus nos fala ao coração.\nTudo canta: Deus é Grande; Deus é bom e Deus é Pai.\n2. É seu Filho Jesus Cristo, que nos une pelo amor, Louvemos o Senhor!\n3. Deus fez comunidade pra vivermos como irmãos,\nBraços dados, todos juntos, caminhamos sem parar.\nJesus Cristo venceu conosco, Ele é jovem como nós, Louvemos o Senhor!\nJesus Cristo é Alegria, Jesus Cristo é o Senhor.\nDa vitória sobre a morte deu a todos o penhor.\nVenceremos a tristeza, venceremos o temor, Louvemos o Senhor!",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $louvorId,
                'ativo'   => true,
            ],
            [
                'numero'  => 63,
                'titulo'  => 'Aleluia',
                'letra'   => "**Aleluia (8x) Jesus Cristo é o Senhor (4x)**\nAleluia (8x) Jesus Cristo é o Senhor (4x)\n*Eu te amo... Sou todo teu, Senhor... Eu te agradeço...*",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 64,
                'titulo'  => 'Jesus Cristo é Meu Amigo',
                'letra'   => "**Jesus Cristo é meu amigo (3x) Aleluia, Aleluia**\n*Ele sempre está comigo... Jesus Cristo é quem perdoa...*\n*Jesus, sim Jesus... Ele é tudo para mim...*\n*Jesus Cristo é meu Senhor... Jesus Cristo é nossa Páscoa...*\n*Vamos todos adorá-Lo... Glória, glória a Jesus Cristo...*",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 66,
                'titulo'  => 'Jesus é Maravilhoso',
                'letra'   => "Jesus é maravilhoso (2x) Ele salva, Ele cura. Ele faz feliz. Sim, Jesus é maravilhoso",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 67,
                'titulo'  => 'Louvado Seja o Meu Senhor',
                'letra'   => "**Louvado seja o meu Senhor... (5x)**\nPor todas suas criaturas, pelo sol e pela lua.\nPelas estrelas no firmamento, pela água e pelo fogo.\nPor aqueles que agora nascem, por aqueles que agora choram\nPor aqueles que sentindo a vida a amar-Te e Louvar-Te.\nPara que a nossa vida seja sempre uma canção.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $louvorId,
                'ativo'   => true,
            ],
            [
                'numero'  => 69,
                'titulo'  => 'Louvai o Criador',
                'letra'   => "**Louvai, louvai, louvai o Criador! Cantai, cantai, cantai a Deus que é nosso Pai!**\n1. Cantai salmos de alegria, cantai salmos de gratidão\nLouvai a Deus que é Pai e nosso irmão.\n2. Louvai homens, terra inteira! Louvai com todo fervor.\nLouvai a Deus que é amor!\n3. Louvai Deus que é criador e irmão. Caminhando em direção ao Deus de amor e esperança. Para o encontro com o irmão.",
                'autor'   => 'Waldeci Farias',
                'tom'     => 'D',
                'tema_id' => $entradaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 70,
                'titulo'  => 'Louvor, Senhor',
                'letra'   => "**Louvor, louvor, Senhor. Louvor, louvor, Senhor (bis)**",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 71,
                'titulo'  => 'Sim, Eu Quero',
                'letra'   => "Sim, eu quero que a luz de Deus que um dia em mim brilhou,\nJamais se apague, meu Senhor, e tudo seja amor!\nSim, eu quero que a luz de Deus que um dia em mim brilhou nunca se apague, meu Senhor, e tudo seja amor!\nMinha alma cheia do amor de Deus, Palpitando a mesma vida divinal.\nO grande segredo do infinito Ser, Meus amigos de setas que são teus, tudo entrego a Ti, ó meu Senhor.",
                'autor'   => 'Pe. José Weber',
                'tom'     => 'D',
                'tema_id' => $comunhaoId,
                'ativo'   => true,
            ],
            [
                'numero'  => 73,
                'titulo'  => 'Louvai Deus',
                'letra'   => "**Louvai Deus, ó criaturas, louvai Deus que nos criou\nLouvai Deus, ó céu, ó estrelas, louvai Deus Nosso Senhor\nExaltai-O e Bendizei-O com alegria e com amor (2x)**\n1. Louvai Deus, louvai ó lua, louvai Deus que nos criou\nLouvai Deus, ó firmamento, louvai Deus Nosso Senhor.\n2. Louvai Deus, ó mar, ó vento, louvai Deus que nos criou\nLouvai Deus, ó noite, ó dia, louvai Deus Nosso Senhor.\n3. Louvai Deus, ó flores, ó aves, louvai Deus que nos criou\nLouvai Deus, ó rios, ó fontes, louvai Deus Nosso Senhor.\n4. Louvai Deus, ó anjos e santos, louvai Deus que nos criou\nLouvai Deus, ó povos, ó homens, louvai Deus Nosso Senhor.",
                'autor'   => 'Pe. Jonas Abib',
                'tom'     => 'D',
                'tema_id' => $louvorId,
                'ativo'   => true,
            ],
            [
                'numero'  => 74,
                'titulo'  => 'O Senhor Fez Em Mim Maravilhas',
                'letra'   => "O Senhor fez em mim maravilhas, Santo é Seu Nome.\nA minha alma engrandece ao Senhor, meu Salvador.\nExulta meu espírito em Deus, meu Salvador.\nPós os olhos na humildade da sua serva, doravante toda a terra cantará os meus louvores.\nO Senhor fez em mim maravilhas, Santo é Seu Nome.\nSeu amor para sempre se estende, sobre aqueles que o temem.\nDemonstrando o poder de seu braço, dispersa os soberbos.\nAbate os poderosos dos tronos e eleva os humildes.\nSacia os bens dos famintos, despede dos ricos sem nada.\nAcolhe Israel seu servidor, fiel a seu amor.\nÉ a promessa que fez a nossos pais, em favor de Abraão e seus filhos para sempre.\nGlória ao Pai, ao Filho e ao Espírito Santo para sempre, amém.",
                'autor'   => 'Gelineau',
                'tom'     => 'D',
                'tema_id' => $mariaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 75,
                'titulo'  => 'Magnificat, Magnificat',
                'letra'   => "**Magnificat, magnificat. É o canto de amor.\nMinha alma engrandece a Deus, meu Salvador.**\n1. Canta coração, alegre e feliz. Com gratidão a Deus bendiz. (bis)\n2. Santo é Seu Nome, que está em toda a terra.\nPuro é seu amor que alegra a alma.\n3. Nossa união é o milagre de amor vindo de Jesus, o nosso Salvador.\n4. Deus é um Pai fiel, de ninguém esquece.\nObrigado, Deus, ouve esta prece. (bis)",
                'autor'   => 'Pe. M. de Espinosa',
                'tom'     => 'D',
                'tema_id' => $mariaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 76,
                'titulo'  => 'Mãe de Todos os Homens',
                'letra'   => "Mãe de todos os homens, ensina-nos a dizer: Amém!\n1. Quando à noite está perto e obscurecida a fé,\n2. Quando a vontade do Pai não é fácil de se fazer,\n3. Quando temos de esquecer-nos para pensar em alguém,\n4. Ao acordar cada dia antes de nada saber,\n5. Se pelo amor dos irmãos devemos algo sofrer.\n6. Quando deitamos à noite, fechando o dia na fé.",
                'autor'   => 'Pe. M. de Espinosa',
                'tom'     => 'D',
                'tema_id' => $mariaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 77,
                'titulo'  => 'Pelas Estradas da Vida',
                'letra'   => "Pelas estradas da vida, nunca sozinho estás,\nContigo pelo caminho, Santa Maria vai. (bis)\n1. Se pelo mundo os homens, sem conhecer-se vão,\nNão negues nunca a tua mão, a quem te encontrar.\n2. Mesmo que digam os homens, tu nada podes mudar,\nLuta por um mundo novo, de unidade e paz.\n3. Se parecer tua vida inútil caminhar,\nLembra que abres caminho, outros te seguirão.",
                'autor'   => 'Pe. M. de Espinosa',
                'tom'     => 'D',
                'tema_id' => $mariaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 78,
                'titulo'  => 'No Teu Altar, Senhor',
                'letra'   => "No teu altar, Senhor, coloco a minha vida em oração.\n1. A alegria de te amar e ser amado, quero em tuas mãos depositar.\n2. O desejo de ser bom e generoso, faz-me viver com mais amor.\n3. Os amigos que me deste e que são teus, tudo entrego a Ti, ó meu Senhor.",
                'autor'   => 'Ir. Míria T. Kolling',
                'tom'     => 'D',
                'tema_id' => $ofertorioId,
                'ativo'   => true,
            ],
            [
                'numero'  => 81,
                'titulo'  => 'Ofertamos ao Senhor',
                'letra'   => "Ofertamos ao Senhor um mundo novo, o futuro do seu povo (bis)\n1. Ofertamos o homem que chora não vendo a aurora do mundo em mudança.\nE ofertamos a esperança dos que descobrem a ressurreição.\n2. Ofertamos o homem que espera por nova era de vida em plenitude,\nE que não tem quem ajude a trocar morte por ressurreição.\n3. Ofertamos a meta e a procura a luta dura entre o velho e o novo.\nA noite escura do povo! E a madrugada da ressurreição.",
                'autor'   => 'Áurea Sigrist',
                'tom'     => 'D',
                'tema_id' => $ofertorioId,
                'ativo'   => true,
            ],
            [
                'numero'  => 82,
                'titulo'  => 'Oi Louvai',
                'letra'   => "**Oi Louvai o Senhor nosso Deus, por tudo aquilo que Ele nos fez (2x)**\n1. Ele nos reuniu no Amor de Cristo,\né sempre fiel ao Seu povo santo.\n2. Ele nos deu o Seu próprio Filho,\ncumpriu Sua Palavra de Salvação.\n3. Ele está presente na nossa história e caminha à frente de Seu povo em marcha.\n4. Ele nos alimenta em nossa caminhada e faz da nossa morte, Vida e Ressurreição.",
                'autor'   => 'Pe. Antonio Haddad',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 83,
                'titulo'  => 'Ofertas Singelas',
                'letra'   => "Ofertas singelas, pão e vinho, sobre a mesa colocamos.\nSinal do trabalho que fizemos e aqui depositamos.\n**É Teu também nosso coração. Aceita, Senhor, a nossa oferta que será, depois, na certa, o Teu próprio Ser (2x)**\nRecebe, Senhor, da natureza todo o fruto que colhemos.\nRecebe o louvor de nossas obras e o progresso que fizemos.\nSabemos que tudo tem valor depois que a terra visitaste,\nembora tivéssemos pecado foi bem mais o que pagaste.",
                'autor'   => 'Pe. Silvino Turco',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 84,
                'titulo'  => 'Oração de São Francisco',
                'letra'   => "Senhor, fazei-me instrumento de vossa paz.\nOnde houver ódio, que eu leve o amor.\nOnde houver ofensa que eu leve o perdão.\nOnde houver discórdia, que eu leve a união.\nOnde houver dúvida, que eu leve a fé.\nOnde houver erro, que eu leve a verdade.\nOnde houver desespero, que eu leve a esperança.\nOnde houver tristeza, que eu leve alegria.\nOnde houver trevas, que eu leve a luz.\nÓ Mestre, fazei que eu procure mais, consolar que ser consolado,\ncompreender que ser compreendido, amar que ser amado.\nPois é dando que se recebe, é perdoando que se é perdoado e é morrendo que se vive para a vida eterna.",
                'autor'   => 'Pe. Iarla',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 86,
                'titulo'  => 'O Pão Que Eu Vos Der',
                'letra'   => "**O Pão que Eu vos der será a minha Carne\nSerá o Pão da Vida que desceu do céu.\nO Pão que Eu vos der será a minha Carne**\n1. Unidos nós estamos, comendo deste Pão,\nPorque acreditamos no Cristo, nosso irmão.\n2. Quem come a minha Carne e bebe o Sangue meu,\nterá a Vida eterna. Foi Cristo que falou.",
                'autor'   => 'Pe. Silvino Turco',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 87,
                'titulo'  => 'Eu Vim Para Que Todos Tenham Vida',
                'letra'   => "\"Eu vim para que todos tenham vida,\nque todos tenham vida plenamente!\"\n1. Reconstrói a tua vida em comunhão com teu Senhor.\nReconstrói a tua vida em comunhão com teu irmão.\nOnde está o teu irmão, Eu estou presente nele.\n2. Eu passei fazendo o bem, eu curei todos os males.\nHoje estou presente junto a todo o sofredor.\n3. Quem comer o Pão da Vida viverá eternamente.",
                'autor'   => 'Pe. José Weber',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 89,
                'titulo'  => 'Pai, Pai',
                'letra'   => "**Pai, Pai, Pai, Pai, eu quero ter um coração de criança (3x)**\nPara amar meu Pai. Um coração bem simples.\nUm coração aberto. Um coração sincero. Um coração fraterno.",
                'autor'   => 'Desconhecido',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 90,
                'titulo'  => 'Para Sempre Nós Louvaremos',
                'letra'   => "**Para sempre nós louvaremos Teu Nome, ó Senhor!**\n1. É fonte de paz e alegria: Teu Nome, ó Senhor.\n2. É vida, verdade e caminho: o Teu eterno amor.\n3. É glória que anela minha alma: o Teu eterno amor.\n4. É luz verdadeira do mundo: Teu nome, ó Senhor.\n5. É guia, bondade, ajuda, o Teu amor.",
                'autor'   => 'Pe. José Weber',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 91,
                'titulo'  => 'Permanecei em Mim',
                'letra'   => "**Permanecei em Mim, é teu pedido Senhor e eu ficarei em vós, é tua promessa de amor (bis)**\n1. Minha vida em tua vida, teu desejo é transformar...\n2. Une em ti, ó meu Senhor, o meu nada com teu Ser...",
                'autor'   => 'Pe. Ney Brasil',
                'tom'     => 'D',
                'tema_id' => $finalId,
                'ativo'   => true,
            ],
            [
                'numero'  => 93,
                'titulo'  => 'Quando o Espírito do Senhor se Move em Mim',
                'letra'   => "**Quando o Espírito do Senhor se move em mim**\n1. Eu rezo como o Rei Davi\n2. Eu canto como o Rei Davi\n3. Eu danço como o Rei Davi\n4. Eu luto como o Rei Davi\n5. Eu venço como o Rei Davi\n6. Eu louvo como o Rei Davi",
                'autor'   => 'Desconhecido',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 94,
                'titulo'  => 'Quando Jesus Passar',
                'letra'   => "**Quando Jesus passar, (3x) eu quero estar no meu lugar...**\n1. No meu telônio ou jogando a rede, sob a figueira ou a caminhar,\nBuscando água pra minha sede, querendo ver meu Senhor passar.\n2. No meu trabalho e na minha casa, no meu estudo e no meu lar,\nNo compromisso e no meu descanso, no meu direito e no meu dever.\n3. Nos meus projetos olhando em frente, no meu sucesso e na decepção,\nNo sofrimento que fere a gente, sonhando o sonho de um mundo irmão.\n4. Com meus amigos, com minha gente, com quem da vida já se cansou,\nA semear e a espalhar sementes na terra onde meu Deus andou.",
                'autor'   => 'Pe. Zezinho',
                'tom'     => 'D',
                'tema_id' => $entradaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 95,
                'titulo'  => 'Sai da Tua Terra',
                'letra'   => "**Sai da tua terra e vai onde te mostrarei (bis)**\n1. Abraão é uma loucura se tu partes: abandonas a tua casa,\nO que esperas encontrar? A estrada é sempre a mesma,\nMas a gente diferente te é inimiga, onde espera de chegar?\n2. O que tu deixas já bem conheces, mas o teu Deus o que te dá?\nUm povo grande, a terra e a promessa: Palavra de Javé.\n3. A rede está na praia abandonada,\nPois aqueles pescadores já seguiram a Jesus;\nE enquanto caminhavam pensativos, no silêncio uma pergunta nasce em cada coração:\nO que deixaste tu bem conheces, mas teu Senhor o que te dá?\n4. O cêntuplo e a mais a eternidade: Palavra de Jesus.\n5. Partir não é tudo, certamente, há quem parte e nada mais;\nBusco só sua liberdade, partir, mas com fé no teu Senhor,\nCom o amor aberto a todos leva ao mundo a Salvação,\nO que deixaste tu bem conheces, o que tu levas é muito mais:\n\"Pregai entre os povãos o Evangelho\" - Palavra de Jesus.",
                'autor'   => 'Pe. José Weber',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 101,
                'titulo'  => 'Segura na Mão de Deus',
                'letra'   => "**Se as águas do mar da vida quiserem te afogar. Segura na mão de Deus e vai!**\n1. Se as tristezas desta vida quiserem te sufocar. Segura na mão de Deus e vai!\n2. É a luz que me sustenta, que me dá força para caminhar,\n3. A voz que me chama e me guia pra longe do mal e da morte.\n4. Segura na mão de Deus e vai, a vida é para quem luta e crê,\n5. É luz que ilumina e clareia o caminho pra chegar até o céu.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $finalId,
                'ativo'   => true,
            ],
            [
                'numero'  => 102,
                'titulo'  => 'Senhor Meu Deus, Obrigado',
                'letra'   => "**Senhor meu Deus, obrigado, Senhor, porque tudo é Teu!**\n1. E Tu é o pão que oferecemos. É Tua a vida que vivemos. Obrigado, Senhor!\n2. E o vinho é o sinal da nossa vida. É Tua a dor que suportamos. Obrigado, Senhor!\n3. A Tua vida é nossa vida, na Tua casa recebida. Obrigado, Senhor!\n4. Na Tua cruz crucificados, sermos Teus ressuscitados. Obrigado, Senhor!",
                'autor'   => 'Pe. Josmar Braga',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 103,
                'titulo'  => 'Salve Rainha',
                'letra'   => "Salve Rainha, Mãe de Deus, és Senhora nossa Mãe,\nnossa doçura, nossa luz, Doce Virgem Maria.\nNós a Ti clamamos, filhos exilados\nNós a Ti voltamos nosso olhar confiante.\nVolta para nós ó Mãe, teus semblante de amor.\nDá-nos teu Jesus ó Mãe, quando a noite passar.\nSalve Rainha, Mãe de Deus, auxílio do Cristão.\nÓ Mãe clemente, Mãe piedosa, doce Virgem Maria.",
                'autor'   => 'José Alves',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 105,
                'titulo'  => 'Ó Céu, a Terra, o Mar',
                'letra'   => "Ó céu, a terra, o mar te louvam, Senhor.\nTe louvam a flor, o fruto, o pão te louvam, Senhor. (bis)\nOs campos ondulando, as ribeiras rolando, Senhor, (bis)\nSerras tão grandiosas que rasgam o azul, te louvam, Senhor. (bis)\nUm hino vibrante de gratidão e louvor.\nTe louva o leito do pobre, do doente, te louvam, Senhor. (bis)\nTe louva o vento, o amor te louvam, Senhor.",
                'autor'   => 'Pe. Jonas Abib',
                'tom'     => 'D',
                'tema_id' => $louvorId,
                'ativo'   => true,
            ],
            [
                'numero'  => 107,
                'titulo'  => 'Senhor, Te Dou a Minha Alegria',
                'letra'   => "Senhor te dou a minha alegria,\npois ela é fruto de paz e amor.\nMuito obrigado, ela é tua, é linda canção do amor.\n**Há alegria (2x) pois trabalhamos por Ti, Senhor. Há alegria (2x) pois nós vivemos no Teu amor.**\n2. Quero sorrir a Ti no imenso riso que passa triste com sua dor.\n3. Sorrir a Ti em mim mesmo para fazer e sempre ser feliz.\n4. Quero servir-Te com alegria, sempre sorrir mesmo sem saber.\n5. Pois o sorriso, embora triste, é bem melhor que não saber sorrir.",
                'autor'   => 'Ir. Míria T. Kolling',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 108,
                'titulo'  => 'Santo, Santo',
                'letra'   => "**Santo (3x) é o Senhor Deus do Universo.**\nO céu e a terra estão cheios da Vossa glória\nHosana nas alturas.\nBendito Aquele que vem em Nome do Senhor.\nHosana nas alturas.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 109,
                'titulo'  => 'Subiremos Montanhas Sagradas',
                'letra'   => "**Subiremos montanhas sagradas, colinas suaves do amor cristão!**\n**Lá do alto, Jesus nos acena, mostrando o caminho da salvação.**\n1. Vamos seguindo para o altar, onde Jesus se dá no pão.\n2. Vamos dizer, pelo cantar, a prece do coração.\nDeus que desceu do alto céu, veio servir-nos de farol\nNeste caminho envolto em véu, em busca do grande sol.",
                'autor'   => 'Pe. Silvino Turco',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 112,
                'titulo'  => 'Vamos Caminhar',
                'letra'   => "**Vamos caminhar a caminho do Senhor. Vamos procurar no amigo o amor.**\n1. Sairemos daqui mais fortes, anda sempre e não te importes\nLevarei tua amizade a caminho do Senhor.\nA estrada é dura e torta, mas o que nos conforta\nÉ seguir juntos a caminho, a caminho do Senhor.\nSeguiremos o caminho que o Senhor nos aplainou\nSofreremos injustiça a caminho do Senhor\nMeu Deus mostrou-me a trilha que me leva ao seu amor\nEntão firme seguirei a caminho do Senhor.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 113,
                'titulo'  => 'Vai Falar no Evangelho',
                'letra'   => "Vai falar no Evangelho Jesus Cristo, aleluia!\nSua Palavra é alimento que dá vida, aleluia!\n**Glória a Ti, Senhor, toda graça e louvor (bis)**\nA mensagem da alegria ouviremos, aleluia!\nDe Deus as maravilhas cantaremos, aleluia!",
                'autor'   => 'Ir. Míria T. Kolling',
                'tom'     => 'D',
                'tema_id' => $aclamacaoId,
                'ativo'   => true,
            ],
            [
                'numero'  => 115,
                'titulo'  => 'Vitória',
                'letra'   => "**Vitória, Tu reinarás! Ó cruz! Tu nos salvarás**\nBrilhando como o lume, que vive sem tua luz.\nÉ luz a cruz bendita, que brilha sobre nós.\nAumenta a confiança, oh pobre e do Senhor.\nCristo ressuscitado é esperança pra o Senhor.\nPor ti no eterno abraço, o Pai nos acolherá.",
                'autor'   => 'David Julien',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 116,
                'titulo'  => 'Vós Sois o Mistério, Senhor',
                'letra'   => "**Vós sois o Mistério, Senhor. Nós vos contemplamos no amor (2x)**\n1. Vinde, Espírito Santo, Vós sois o amor do Pai e do Filho,\no Espírito de comunhão.\n2. Vinde Espírito Santo, Vós sois o Mistério de Amor,\nQue dá vida e fecundidade.\n3. Vinde Espírito Santo, Vós sois a Luz que nos ilumina\ne nos aquece no Seu fogo abrasador.\n4. Vinde Espírito Santo, Vós sois o Deus que nos invade,\nComo o vento que sopra onde quer.",
                'autor'   => 'Vicente/A. Haddad',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 118,
                'titulo'  => 'Vem, e Eu Mostrarei',
                'letra'   => "1. Vem, e eu mostrarei que o meu caminho te leva ao Pai, onde guiareis os passos teus e junto a ti hei de seguir.\n*Sim, eu irei e saberei como chegar ao fim. De onde vim, aonde vou; por onde irás, irei também.*\n2. Vem, e eu te direi o que ainda estás a procurar.\nA verdade é como o sol e invadirá teu coração.\n*Sim, eu irei e aprenderei minha razão de ser. Eu creio em Ti que crês em mim e à Tua luz verei a luz.*",
                'autor'   => 'Waldeci Farias',
                'tom'     => 'D',
                'tema_id' => $comunhaoId,
                'ativo'   => true,
            ],
            [
                'numero'  => 119,
                'titulo'  => 'O Cativeiro',
                'letra'   => "**O cativeiro, o cativeiro, o cativeiro acabou!**\n1. Há risos e cantos e muito louvor, o cativeiro acabou!\n2. Minha triste esperança e muita alegria, o cativeiro acabou!",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 120,
                'titulo'  => 'Jesus Cristo É o Senhor',
                'letra'   => "**Jesus Cristo é o Senhor, o Senhor, o Senhor.\nJesus Cristo é o Senhor, Glória a Ti, Senhor.**\n1. Da minha vida Ele é o Senhor (3x) Glória a Ti Senhor.\n2. Do meu passado Ele é o Senhor (3x) Glória a Ti Senhor.\n3. Do meu presente Ele é o Senhor (3x) Glória a Ti Senhor.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 121,
                'titulo'  => 'Este É o Dia',
                'letra'   => "Este é o dia (bis) que o Senhor nos fez (bis)\nDia de alegria (bis) e de cânticos (bis)\nEste é o dia (bis) que o Senhor nos fez, dia de alegria e cânticos.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $entradaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 122,
                'titulo'  => 'Jesus Cristo Não Vai Passar',
                'letra'   => "**Jesus Cristo não vai passar (3x) Porque está dentro do meu coração!**\nO fogo cai, cai, cai. Os males saem, saem, saem, sai porque cremos louvor ao Senhor.\nO Espírito... O Evangelho... A fé... A esperança... O amor...",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $finalId,
                'ativo'   => true,
            ],
            [
                'numero'  => 123,
                'titulo'  => 'Alegrai-vos Sempre',
                'letra'   => "**Alegrai-vos sempre no Senhor, alegrai-vos no Senhor (2x)\nAlegrai-vos, alegrai-vos, alegrai-vos no Senhor (2x)**",
                'autor'   => 'Pe. Jonas Abib',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 126,
                'titulo'  => 'Pai, Eu Te Adoro',
                'letra'   => "Pai, eu te adoro, Te ofereço a minha vida, como eu Te amo\nCristo... Espírito... Trindade...",
                'autor'   => 'Luteran Intl',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 127,
                'titulo'  => 'Põe Tua Mão',
                'letra'   => "**Põe tua mão na mão do meu Senhor da Galiléia**\n(Põe tua mão na mão do meu Senhor que acalma o mar)\nMeu Jesus que cuida de mim, sempre é dia sem cessar.\nPõe tua mão na mão do meu Senhor que acalma o mar.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $entregaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 128,
                'titulo'  => 'Basta Que Me Toques',
                'letra'   => "Basta que me toques Senhor\n*Minha alma fortalecerás, se a noite escura está Tua presença me guiará...*\n1. Basta que me olhes, Senhor.\n2. Basta que me ames, Senhor.\n3. Basta que eu te encontre, Senhor.\n4. Basta que eu te busque, Senhor.\n5. Basta que eu te fale, Senhor.\n6. Basta que eu te siga, Senhor.\n7. Basta que Te adore, Senhor.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 129,
                'titulo'  => 'Senhor, Quem Entrará',
                'letra'   => "Senhor, quem entrará no santuário pra te louvar?\nQuem tem as mãos limpas, e o coração puro,\nsem vaidade e fé, sabe amar.\n2. Senhor, eu quero entrar no santuário pra te louvar\ncom as mãos limpas, e um coração puro,\narranca a vaidade, ensina-me a amar.\n3. Senhor, já posso entrar no Santuário pra te louvar.\nTeu Sangue me lava, Teu fogo me queima.\nO Espírito Santo inunda meu ser.",
                'autor'   => 'Pe. Jonas Abib',
                'tom'     => 'D',
                'tema_id' => $entradaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 130,
                'titulo'  => 'Ó Senhor, Aceita o Louvor',
                'letra'   => "**Ó Senhor aceita o louvor que parte dentro de minha alma (2x)**\nEu sei que a tempestade se acalma quando eu glorifico, louvando o Senhor (2x)",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $louvorId,
                'ativo'   => true,
            ],
            [
                'numero'  => 131,
                'titulo'  => 'Eu Louvarei',
                'letra'   => "**Eu louvarei (5x) o meu Senhor (bis)**\n1. João viu o número dos redimidos e todos louvavam o Senhor.\n2. Todos unidos, alegres, cantavam glória e louvores ao Senhor!\nGlória ao Pai, glória ao Filho, glória ao Espírito de Amor.\n3. Somos filhos de Ti, Pai Eterno. Tu nos criaste por amor.\nNossos nomes estão inscritos e todos terão teu louvor.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $louvorId,
                'ativo'   => true,
            ],
            [
                'numero'  => 132,
                'titulo'  => 'Cristo Tem Poder',
                'letra'   => "**Cristo tem poder (3x) Aleluia! Tem poder!\nCristo tem poder (2x) Jesus Cristo é poderoso,\nJesus Cristo tem poder!**\n1. Na cidade de Naim tinha uma mulher chorando, seu filho ia pro túmulo e o povo carregando.\nJesus parou o enterro e o povo reprovou. Jesus chamou o morto e o morto levantou. Por quê?\n2. Jesus curou um cego entrando em Jericó. Salvou a Samaritana lá no poço de Jacó\nNo monte das Oliveiras seu poder mostrou, cinco pães e dois peixinhos dividiu. Por quê?\n3. Jesus fez maravilhas no deserto da Judéia, e em Cafarnaum milagre também fez.\nE curou lá no caminho dez leprosos de uma vez. Por quê?\n4. Jesus fez maravilhas, está fazendo e vai fazer. Não faz em sua vida só porque você não crê.\nEle salva o pecador, dá alegria, gozo e paz. Cura as enfermidades, e expulsa satanás. Por quê?",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 133,
                'titulo'  => 'Livre, Me Deixaste Livre',
                'letra'   => "No Egito escravo eu fui, sim, sim, oh sim. No Egito escravo eu fui do rei Faraó.\n*Triste, bem triste estava, meu coração chorava, liberta-me Senhor* (bis)\n2. Moisés foi ao Faraó, sim, sim. Moisés foi ao Faraó, ele lhe disse assim:\n*Deixa meu povo ir para prestar-me culto a mim que sou o Senhor* (bis)\n3. Faraó, se não libertasse, oh sim, Faraó se endurecesse, e não os deixaria ir.\nDeus enviou dez pragas, desembainhou sua espada, deu-lhes a liberdade (bis)\n4. Agora que livre estou, sim, sim, sim, Agora que livre estou, livre para Ti\nQuero prestar-Te culto, quero cantar-Te glória, glória a Ti Senhor (bis)\nGlória, Glória Aleluia, Glória Aleluia a Ti Senhor. (bis)\nLivre, me deixaste livre, me deixaste livre, livre, livre, Senhor. (bis)",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 134,
                'titulo'  => 'Jesus de Nazaré',
                'letra'   => "Jesus, Jesus de Nazaré, o teu semblante eu quero ter.\nTua luz e teu querer sou, Jesus, Jesus de Nazaré.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 135,
                'titulo'  => 'Jesus, Jesus',
                'letra'   => "Jesus (2x) eu agora venho a Ti.\nTrazido por teu infinito amor.\nTu me dás de Tuas riquezas e eu Te amo tanto.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 137,
                'titulo'  => 'Buscai Primeiro',
                'letra'   => "Buscai primeiro o Reino de Deus e a sua justiça\nE tudo mais vos será acrescentado, Aleluia, Aleluia.\nNão só de pão o homem viverá, mas de toda palavra.\nQue procede da boca de Deus, Aleluia, Aleluia.",
                'autor'   => 'M. Frankreich',
                'tom'     => 'C',
                'tema_id' => $aclamacaoId,
                'ativo'   => true,
            ],
            [
                'numero'  => 139,
                'titulo'  => 'Ao Orarmos',
                'letra'   => "Ao orarmos, Senhor, vem encher-nos com teu amor,\nO mundo agitado esquecer. Cada dia tua vida viver nossas vidas vêm transformar:\nrefrígerio pra alma nos dar.\nEm oração, com outros irmãos, aos rumos aqui em oração.",
                'autor'   => 'Ralph Carmichael',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 140,
                'titulo'  => 'Minha Paz Vos Dou',
                'letra'   => "Minha paz vos dou (bis) não como o mundo, eu vô-la dou, minha paz vos dou.\n1. A fé vos dou (bis) não como o mundo, eu vô-la dou, a fé vos dou.\n3. Esperança vos dou (bis) não como o mundo, eu vô-la dou, esperança vos dou.",
                'autor'   => 'J. Hauser',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 141,
                'titulo'  => 'Pai de Amor',
                'letra'   => "Pai de amor, gosto tanto de Ti (bis) te amo, te quero e prostrado te adoro,\nPai de amor, gosto tanto de Ti.\n2. Meu Jesus amoroso Tu és (bis), minh’alma já limpaste e o Espírito enviaste, Meu Jesus amoroso Tu és.\n3. Santo Espírito Consolador (bis) Tu nos santificas e em nós sempre habitas,\nSanto Espírito Consolador.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $adoracaoId,
                'ativo'   => true,
            ],
            [
                'numero'  => 142,
                'titulo'  => 'Faze-me Chegar',
                'letra'   => "Faze-me chegar aos teu rios, Senhor (3x)\nFaze-me chegar, faze-me beber, faze-me viver.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 133,
                'titulo'  => 'Livre, Me Deixaste Livre',
                'letra'   => "No Egito escravo eu fui, sim, sim, oh sim. No Egito escravo eu fui do rei Faraó.\n*Triste, bem triste estava, meu coração chorava, liberta-me Senhor* (bis)\n2. Moisés foi ao Faraó, sim, sim. Moisés foi ao Faraó, ele lhe disse assim:\n*Deixa meu povo ir para prestar-me culto a mim que sou o Senhor* (bis)\n3. Faraó se não libertasse, oh sim, Faraó se endurecesse, e não os deixaria ir.\nDeus enviou dez pragas, desembainhou sua espada, deu-lhes a liberdade (bis)\n4. Agora que livre estou, sim, sim, sim, Agora que livre estou, livre para Ti\nQuero prestar-Te culto, quero cantar-Te glória, glória a Ti Senhor (bis)\nGlória, Glória Aleluia, Glória Aleluia a Ti Senhor. (bis)\nLivre, me deixaste livre, me deixaste livre, livre, livre, Senhor. (bis)",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],

            [
                'numero'  => 134,
                'titulo'  => 'Jesus de Nazaré',
                'letra'   => "Jesus, Jesus de Nazaré, o teu semblante eu quero ter.\nTua luz e teu querer sou, Jesus, Jesus de Nazaré.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],

            [
                'numero'  => 135,
                'titulo'  => 'Jesus, Jesus',
                'letra'   => "Jesus (2x) eu agora venho a Ti.\nTrazido por teu infinito amor.\nTu me dás de Tuas riquezas e eu Te amo tanto.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],

            [
                'numero'  => 137,
                'titulo'  => 'Buscai Primeiro',
                'letra'   => "Buscai primeiro o Reino de Deus e a sua justiça\nE tudo mais vos será acrescentado, Aleluia, Aleluia.\nNão só de pão o homem viverá, mas de toda palavra.\nQue procede da boca de Deus, Aleluia, Aleluia.",
                'autor'   => 'M. Frankreich',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],

            [
                'numero'  => 139,
                'titulo'  => 'Ao Orarmos',
                'letra'   => "Ao orarmos, Senhor, vem encher-nos com teu amor,\nO mundo agitado esquecer. Cada dia tua vida viver nossas vidas vêm transformar:\nrefrígerio pra alma nos dar.\nEm oração, com outros irmãos, aos rumos aqui em oração.",
                'autor'   => 'Ralph Carmichael',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],

            [
                'numero'  => 140,
                'titulo'  => 'Minha Paz Vos Dou',
                'letra'   => "Minha paz vos dou (bis) não como o mundo, eu vô-la dou, minha paz vos dou.\n1. A fé vos dou (bis) não como o mundo, eu vô-la dou, a fé vos dou.\n3. Esperança vos dou (bis) não como o mundo, eu vô-la dou, esperança vos dou.",
                'autor'   => 'J. Hauser',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],

            [
                'numero'  => 141,
                'titulo'  => 'Pai de Amor',
                'letra'   => "Pai de amor, gosto tanto de Ti (bis) te amo, te quero e prostrado te adoro,\nPai de amor, gosto tanto de Ti.\n2. Meu Jesus amoroso Tu és (bis), minh’alma já limpaste e o Espírito enviaste, Meu Jesus amoroso Tu és.\n3. Santo Espírito Consolador (bis) Tu nos santificas e em nós sempre habitas,\nSanto Espírito Consolador.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],

            [
                'numero'  => 142,
                'titulo'  => 'Faze-me Chegar',
                'letra'   => "Faze-me chegar aos teu rios, Senhor (3x)\nFaze-me chegar, faze-me beber, faze-me viver.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 143,
                'titulo'  => 'Cantai ao Senhor',
                'letra'   => "**Cantai ao Senhor um cântico novo (3x) cantai ao Senhor, cantai ao Senhor**\n1. Cantai ao Senhor um cântico novo (3x) cantai ao Senhor, cantai ao Senhor.\n2. Porque Ele fez, Ele faz maravilhas (3x) cantai ao Senhor, cantai ao Senhor.\n3. Ele quem dá o Espírito Santo (3x) cantai ao Senhor, cantai ao Senhor.\n4. Cantai ao Senhor, Amém, Aleluia (3x) louvai ao Senhor, louvai ao Senhor.\n5. Louvai o Senhor, Amém, Aleluia (3x) louvai ao Senhor, louvai ao Senhor.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $meditacaoId,
                'ativo'   => true,
            ],
            [
                'numero'  => 151,
                'titulo'  => 'Demos Graças ao Senhor',
                'letra'   => "**Demos graças ao Senhor, demos graças, demos graças, demos graças ao Senhor (bis)**\n1. Pela manhã as aves cantam alegremente a Cristo Salvador.\n2. Pela noite os grilos cantam em grande orquestra na festa do Senhor. (bis)\n3. No mundo inteiro os homens cantam as maravilhas do Deus que nos amou.",
                'autor'   => 'Pe. Jonas Abib',
                'tom'     => 'D',
                'tema_id' => $louvorId,
                'ativo'   => true,
            ],
            [
                'numero'  => 153,
                'titulo'  => 'Estamos em Festa',
                'letra'   => "Estamos em festa com Jesus, ao céu os hinos vão subir.\nEstamos em festa com Jesus, o nosso Rei é Cristo quem vai servir.\nPoderoso é nosso Deus. (4x) Ele cura, ele salva, Poderoso é nosso Deus.\n**Poderoso (3x) Deus. (4x) Poderoso, Poderoso, amoroso é nosso Deus. (3x)**\nPeça que Jesus aumente o amor demais. Outorga a todos sua amizade.\nRecuso viver sem o Senhor. Sua justiça é fiel, justiça é vida.\nEstamos alegres com Jesus. Amigo não há melhor.\nSua vida e a minha vida, unidas. Cantemos ao Salvador.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $entradaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 155,
                'titulo'  => 'Eu Te Digo',
                'letra'   => "Eu te digo que se creres verás a Glória de Deus\n**Verás a glória de Deus, verás (2x)**\n1. Eu te digo se jejuaras verás a Glória de Deus\n2. Eu te digo se orares verás a Glória de Deus\n3. Eu te digo se amares verás a Glória de Deus\n4. Eu te digo se perdoares verás a Glória de Deus\n5. Eu te digo se te humilhares verás a Glória de Deus.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 156,
                'titulo'  => 'Eu Tenho um Gozo em Minh\'Alma',
                'letra'   => "**Eu tenho um gozo em minh'alma, gozo em minh'alma, gozo em minh'alma e eu canto, sim Senhor. Aleluia, glória a Deus.**\n**É como um rio de água viva, rio de água viva, rio de água viva borbulhando em meu ser.**\n1. Vamos cantando e sentindo o seu amor. (bis)\nDá glória a Deus (glória a Deus) Dá glória a Ele.\n2. Não te envergonhes de louvar o teu Senhor (2x)",
                'autor'   => 'Pe. Jonas Abib',
                'tom'     => 'D',
                'tema_id' => $louvorId,
                'ativo'   => true,
            ],
            [
                'numero'  => 157,
                'titulo'  => 'Eu Tenho um Amigo Que Me Ama',
                'letra'   => "Eu tenho um amigo que me ama; me ama, me ama!\nEu tenho um amigo que me ama! Seu Nome é Jesus.\nQue me ama, que me ama, que me ama com eterno amor.\nTu tens um amigo que te ama, que te ama, que te ama com eterno amor.\nO Nome é Jesus.\nNós temos um amigo que nos ama, nos ama, nos ama com eterno amor.\nO Nome é Jesus.",
                'autor'   => 'Pe. Jonas Abib',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 161,
                'titulo'  => 'Ouro e Prata Não Tenho',
                'letra'   => "Ouro e prata não tenho, mas o que tenho te dou!\nFoi andando, saltando Em Nome de Jesus Cristo: levanta-te e anda!",
                'autor'   => 'Pe. Jonas Abib',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 162,
                'titulo'  => 'Passa por Aqui',
                'letra'   => "1. Ó Senhor, passa por aqui, Senhor, passa por aqui (2x)\n2. Enche-me de Ti, Senhor, enche-me de Ti (2x)\n3. Ó Senhor, toma-me em Tuas mãos (2x)\n4. Ó Senhor, seja tudo em mim (2x)\n5. Senhor, eu me entrego a Ti (2x)",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 164,
                'titulo'  => 'Ressuscitou',
                'letra'   => "**Ressuscitou (3x) Aleluia, Aleluia, Aleluia, Aleluia, Ressuscitou.**\n1. Ó morte, onde estás, ó morte? Quem és tu, ó morte? Qual a tua vitória?\nAleluia! Somos alegres, hoje cantamos, o Senhor ressurgiu! Aleluia!\n2. Com Cristo, nós ressuscitamos, juntos proclamamos: o Senhor nos salvou.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $aclamacaoId,
                'ativo'   => true,
            ],
            [
                'numero'  => 167,
                'titulo'  => 'Senhor, Meu Deus',
                'letra'   => "**Senhor, meu Deus, te entrego meu coração.**\nSenhor, meu Deus, teu povo se alegra em Ti.\n1. Senhor, ó Deus, Filho de Deus, Tu és o meu Salvador. Te entrego meu coração.\n2. Ó Rei da vitória, Deus vivo, imortal, da morte triunfador, te entrego meu coração.\n3. Ó rio d’água viva, fluente de vida, Tu és o batizado, te entrego meu coração.",
                'autor'   => 'Pe. Jonas Abib',
                'tom'     => 'D',
                'tema_id' => $entregaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 168,
                'titulo'  => 'Senhor, Tu És Meu Deus',
                'letra'   => "**Senhor, Tu és meu Deus, cantarei e exaltarei Teu Nome (3x)**\nPorque fazes maravilhas, cantarei e exaltarei Teu Nome (3x)",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 169,
                'titulo'  => 'Sou Feliz',
                'letra'   => "Sou feliz, Ele me libertou (3x) Canto glória, aleluia! Ele me libertou.\nSou feliz, Ele por mim morreu (3x) Canto glória, aleluia! Ele por mim morreu.\nSou feliz, Ele ressuscitou (3x) Canto glória, aleluia! Jesus ressuscitou.\nSou feliz, Cristo abriu o céu (3x) Canto glória, aleluia! Cristo abriu o Céu.\nSou feliz, Cristo vive em mim (3x) Canto glória, aleluia! Cristo vive em mim.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 170,
                'titulo'  => 'Sou Testemunha',
                'letra'   => "Sou testemunha do poder de Deus, pelo milagre que Ele fez em mim.\nEstava cego, mas agora vejo a luz, a luz gloriosa que me deu Jesus.\nNão, não, nunca, nunca, nunca, nunca me deixará.\nNunca, nunca me desamparará. Na noite escura, ou no dia de prova,\nJesus Cristo nunca me desamparará. (bis)",
                'autor'   => 'Pe. Jonas Abib',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 171,
                'titulo'  => 'Tão Grande és, Meu Deus',
                'letra'   => "**Tão grande és, meu Deus, Tão grande és, meu Pai. Bondade sem fim, amor sem igual.**\nFizeste a promessa de jamais me deixar. Sim nunca me abandonas, Deus fiel serás.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 173,
                'titulo'  => 'Tu Me Conheces',
                'letra'   => "Tu me conheces quando estou sentado, Tu me conheces quando estou de pé.\nVês claramente quando estou andando, quando repouso tu também me vês.\nMeus passos todos que dou, são conhecidos, tanto de frente sei que me percebes.\nPara ficar longe do teu Espírito. O que farei? Aonde irei, aonde estou?\n**Para onde irei? Para onde fugirei? Se subo ao céu ou se me prosto no abismo, Eu te encontro lá. Para onde irei? Para onde fugirei? Se estás no alto da montanha verdejante ou no mais fundo do mar.**\nPara ti a noite é clara como o dia, nada se oculta ao teu divino olhar,\nTeus olhos me acompanham sempre, e me vês viver, Senhor, só tu.\nDá-me tuas mãos, ó meu Senhor bendito, ensina-me teus caminhos, Senhor.\nRemove Deus o véu de minha mente, quero viver a esperança, quero sorrir, cantar.\nLivra-me de todo mal, caminhe agora ao lado meu, Senhor.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $meditacaoId,
                'ativo'   => true,
            ],
            [
                'numero'  => 174,
                'titulo'  => 'Não Há Deus Tão Grande',
                'letra'   => "1. Não há Deus tão grande como Tu, não, não há, não, não há (2x)\n2. Não há Deus que possa fazer coisas, como as que fazes Tu (2x)\n3. Estes montes se moverão, com Teu Santo Espírito (2x)\n4. Estes montes se moverão, com Teu Santo Espírito.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $louvorId,
                'ativo'   => true,
            ],
            [
                'numero'  => 176,
                'titulo'  => 'Irmão Sol Com Irmã Luz',
                'letra'   => "Irmão sol com irmã luz, trazendo o dia pela mão.\nIrmão céu, de intenso azul a invadir o coração. Aleluia.\n**Irmãos, minhas irmãs, vamos cantar nesta manhã,\nPois renasceu mais uma vez a criação das mãos de Deus.\nIrmãos, minhas irmãs, vamos cantar: Aleluia, Aleluia, Aleluia.**\n2. Minha irmã terra, que ao pé dá segurança de chegar,\nMinha irmã planta que está suavemente a respirar. Aleluia.\n3. Irmã flor que mal se abriu já é o amor que não tem fim.\nÁgua irmã, que nos refaz e sai do chão cantando assim: Aleluia.\n4. Passarinhos, meus irmãos, com mil canções a ir e vir,\nHomens, todos, meus irmãos, que sons você se faça ouvir. Aleluia.",
                'autor'   => 'Dom Navarro',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 177,
                'titulo'  => 'Maria de Nazaré',
                'letra'   => "Maria de Nazaré, Maria me cativou. Fez mais forte a minha fé\ne por filho me adotou. Às vezes eu paro e fico a pensar e sem perceber me vejo a rezar e o meu coração se põe a cantar. Pra virgem de Nazaré.\nMenina que Deus amou e escolheu pra Mãe de Jesus, o Filho de Deus,\nMaria que o povo inteiro elegeu, Senhora e Mãe do céu.\n*Ave Maria (3x) Mãe de Jesus.*\n2. Maria que eu quero bem, Maria do puro amor,\nIgual a você ninguém, mãe pura do meu Senhor.\nEm cada mulher que a terra criou um traço de Deus Maria deixou,\nUm sonho, um toque de mãe Maria plantou pro mundo encontrar a paz.\nMaria que fez o Cristo falar, Maria que fez Jesus caminhar.\nMaria que só viveu pra Jesus, Maria do povo meu.",
                'autor'   => 'Pe. Zezinho',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 178,
                'titulo'  => 'Vocação',
                'letra'   => "1. Se ouvires a voz do vento, chamando sem cessar. A decisão é tua (x2) São muitos os convidados (2x) Quase ninguém tem tempo (2x)\n2. Se ouvires a voz do tempo, mandando esperar. A decisão é tua (x2) São muitos os convidados (2x) Quase ninguém tem tempo (2x)\n3. Se ouvires a voz de Deus chamando sem cessar. A decisão é tua (x2) São muitos os convidados (2x) Quase ninguém tem tempo (2x)\n4. Se ouvires a voz do mundo, querendo te enganar. A decisão é tua (2x) O trigo já se perdeu. Cresceu ninguém colheu. A decisão é tua (2x)\n5. Se ouvires a voz do mundo, passando fome de Deus. A decisão é tua (2x)",
                'autor'   => 'Pe. Zezinho',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 185,
                'titulo'  => 'Seduziste-me, Senhor',
                'letra'   => "**Seduziste-me, Senhor, e me deixei seduzir; uma luta desigual dominaste-me, Senhor. E foi tua a vitória.**\n1. Vantagens e honras só perdias para mim, diante do conhecimento da justiça de Deus que nasce da fé em Cristo.\n2. Nada que eu conheço ainda mais forte é o amor que me faz viver.\nSei que conhecê-lo é sofrer e morrer com Ele, mas a vida é mais forte.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 188,
                'titulo'  => 'Ó Mãe, Neste Dia',
                'letra'   => "**Ó Mãe de Jesus, nós queremos cantar, com grande alegria teu Nome exaltar, unidos aos anjos que cantam no além, és feliz no céu e na terra também.**\n1. Na Encarnação te entregaste ao Senhor, à sua vontade aderiste com ardor.\n2. Na Visitação prorrompeste em louvor, ao Deus que de Ti fizera um primor.\n3. De Jesus a Palavra guardavas na mente, a graça crescia em tua alma ardente.",
                'autor'   => 'Ir. Damião',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 189,
                'titulo'  => 'Sabes, Senhor',
                'letra'   => "**Sabes, Senhor, o que temos é tão pouco para dar, mas este pouco, nós queremos com os irmãos compartilhar.**\n1. Queremos nesta hora diante dos irmãos comprometer a vida, buscando a união.\n2. Sabemos que é difícil os bens compartilhar; mas com a tua graça, Senhor, queremos dar.\n3. Olhando teu exemplo, Senhor, vamos seguir, fazendo o bem a todos, sem nada exigir.",
                'autor'   => 'Ir. Lindbergh Pires',
                'tom'     => 'D',
                'tema_id' => $ofertorioId,
                'ativo'   => true,
            ],
            [
                'numero'  => 190,
                'titulo'  => 'Abre a Porta do Teu Coração',
                'letra'   => "Abre a porta do teu coração e deixa Cristo entrar. Ele te dará salvação e ao céu te levará.\n**Abre a porta (3x) do teu coração\nAbre a porta (3x) que Jesus te abençoará.**\nAbre a porta do teu coração e deixa Cristo em ti habitar.\nAbre a porta do teu coração que Jesus te abençoará.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 192,
                'titulo'  => 'Eu Só Confio no Senhor',
                'letra'   => "1. Eu só confio no Senhor que não vai falhar.\nEu só confio no Senhor sigo a cantar.\nSe o sol chegar a escurecer e o céu nublar,\neu só confio no Senhor que não vai falhar.\n**Posso confiar (2x) que um lar no céu Cristo vai me dar.\nSe o sol chegar a escurecer e o céu nublar,\neu só confio no Senhor que não vai falhar.**\n2. Confiando no meu Senhor eu não temo o mal.\nConfiando no meu Senhor tenho paz real.\nPois o mal vier me perturbar, n’Ele confiarei.\nSó a Jesus me entreguei, Ele é meu Rei.\n**Agora sou feliz (2x) Como sou feliz (2x)\nCristo me salvou (2x) Vencedor eu sou (2x)**",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 194,
                'titulo'  => 'O Nome de Jesus é Doce',
                'letra'   => "O nome de Jesus é doce, traz gozo, paz e alegria,\ncantando essa melodia, Jesus, Jesus, Jesus.\nSubindo, subindo até o céu vou pro Senhor.\nTristeza não vai comigo, porque Jesus já me libertou (2x)\nJoguei a tristeza fora e em paz agora contente estou. (2x)",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 195,
                'titulo'  => 'Dê um Sorriso Só',
                'letra'   => "Dê um sorriso só, sorriso aberto, sorriso certo, cheio de amor (2x)\nQuem tem Jesus, gosta de cantar, está sempre sorrindo mesmo quando não dá.\nTropeça aqui, cai ali, a comida acaba, mas depressa levanta e começa a cantar.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 196,
                'titulo'  => 'Povo de Deus',
                'letra'   => "**Povo de Deus, abre o coração, és povo santo\nEsquece o pecado e canta o baião**\n1. Aprendemos na Bíblia que o Cristo é o Messias, o libertador\n2. Ele é nosso Mestre, com Ele se aprende a viver no amor.\n3. Somos filhos de Deus e nossos irmãos são gente de bem\nVamos lutar por ser bem melhor o mundo que vem\n4. O povo todo se unindo, formando esta Igreja, ela há de crescer\nA luta está dura, mas Deus está conosco, nós vamos vencer",
                'autor'   => 'Frei Chico',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 199,
                'titulo'  => 'Ele Vive',
                'letra'   => "Eu canto de alegria, a pérola preciosa achei. Por isso eu preciso cantar:\nMeu Cristo eu encontrei. Ele vive, Ele vive, eu sei que o meu\nCristo vive em mim. Eu sei que vive, Ele vive, Ele vive em meu ser.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 200,
                'titulo'  => 'Abençoa-nos Senhor',
                'letra'   => "1. .......... será abençoado, porque o Senhor vai derramar o Seu Amor. (bis)\n2. Derrama Senhor, derrama Senhor: Derrama sobre ele o Seu Amor. (bis)\n3. .......... já foi abençoado, porque o Senhor já derramou o Seu Amor. (bis)",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 203,
                'titulo'  => 'Todos Precisam Saber',
                'letra'   => "**Todos precisam saber (3x) quem é Jesus\nEle é o lírio do vale, Ele é a estrela da manhã\nEle é a fonte de água viva, todos precisam saber\nAgora eu sei (3x) quem é Jesus**",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 204,
                'titulo'  => 'Eis Que Estou à Porta e Bato',
                'letra'   => "Eis que estou à porta e bato em sua morada.\nVocê não me conhece e não sabe de onde eu venho.\nEu sou Jesus, eu sou a Vida. **Eu sou a paz, eu sou o amor! (2x)**\nAbra a sua porta e deixe que eu entre. Eu é só eu posso lhe dar felicidade.\nSe eu fizer morada é viver com sua casa. Você saberá o que é paz e alegria.",
                'autor'   => 'Músicas Católicas',
                'tom'     => 'D',
                'tema_id' => $comunhaoId,
                'ativo'   => true,
            ],
            [
                'numero'  => 206,
                'titulo'  => 'A Barca',
                'letra'   => "1. Tu, te abeiraste da praia, não buscaste nem sábios nem ricos, somente queres que eu te siga.\n**Senhor, tu me olhaste nos olhos, a sorrir, pronunciaste meu Nome, lá na praia, eu larguei o meu barco, junto a Ti buscarei outro mar.**\n2. Tu sabes bem que em meu barco eu não tenho nem ouro nem espadas, somente redes e o meu trabalho.\n3. Tu, minhas mãos solicitas, meu cansaço que a outros descanse, amor que almeja seguir amando.\n4. Tu, pescador de outros lagos, ânsia eterna de almas que esperam, bom amigo que assim me chamas.",
                'autor'   => 'Cesáreo Gabarin',
                'tom'     => 'D',
                'tema_id' => $comunhaoId,
                'ativo'   => true,
            ],
            [
                'numero'  => 207,
                'titulo'  => 'Estaremos Aqui Reunidos',
                'letra'   => "**Estaremos aqui reunidos, como estavam em Jerusalém.**\nÉ o Espírito quando vivemos unidos, que o Espírito Santo nos vem.\n1. Ninguém vive para esse viver, ninguém morre por morrer,\numa verdade se tem: nós somos corpo e assim bem unidos,\nnesta certeza: a cabeça é Jesus.\n2. Fez da minha Igreja a sua igreja, o povo é o povo de Deus.\nNele a promessa que o Espírito Santo habita; e o Espírito Santo, guia e conduz.\n3. Fez da minha casa a sua casa, o caminho para a nossa união.\n4. Quando o Espírito espalha suas graças, faz dos povos um só coração;\né o Espírito quem nos dá força, todas as raças um só Deus, um só Pai louvarão.",
                'autor'   => 'Lúcio Fiore/Ir. Míria Kolling',
                'tom'     => 'D',
                'tema_id' => $entradaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 209,
                'titulo'  => 'Sobe a Jerusalém',
                'letra'   => "1. Sobe a Jerusalém, Virgem oferente sem igual\nVai apresenta ao Pai teu Menino: Luz que chegou no Natal.\nE, junto à sua cruz, quando Deus morrer fica de pé.\nSim, Ele te salvou, mas O ofereceste por nós com tua fé.\n2. Nós vamos renovar este sacrifício de Jesus: Morte e Ressurreição;\nvida nova brotou de sua oferta na Cruz.\nMãe, nós ensinara a fazer da vida uma oblação;\nCulto agradável a Deus é fazer a oferta do próprio coração.",
                'autor'   => 'Waldeci Farias/Dom Navarro',
                'tom'     => 'D',
                'tema_id' => $ofertorioId,
                'ativo'   => true,
            ],
            [
                'numero'  => 210,
                'titulo'  => 'Que Poderei Retribuir ao Senhor',
                'letra'   => "Que poderei retribuir ao Senhor por tudo aquilo que Ele me deu?\n**Oferecerei o seu sacrifício e invocarei o seu santo Nome.**\n1. O que poderei oferecer ao meu Deus pelos imensos benefícios que me fez?\n2. Eu cumprirei minha promessa ao Senhor na reunião do povo santo de Deus.\n3. Vós me quebrastes os grilhões de escravidão,\né por isso que hoje canto vosso Amor.",
                'autor'   => 'Pe. José Weber',
                'tom'     => 'D',
                'tema_id' => $ofertorioId,
                'ativo'   => true,
            ],
            [
                'numero'  => 211,
                'titulo'  => 'Bom é Louvar',
                'letra'   => "**Bom é louvar o Senhor nosso Deus, cantar salmos ao Nome do Altíssimo\nCom alegria aclamar Seu amor, Sua glória, bondade e poder.**",
                'autor'   => 'Pe. Ney Brasil',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 212,
                'titulo'  => 'Comei, Tomai',
                'letra'   => "1. Eu quis comer esta ceia agora, pois vou morrer já chegou minha hora.\n**Comei, tomai, é meu corpo e meu sangue que dou,\nvivei no amor, eu vou preparar a ceia na casa do Pai. (bis)**\n2. E vai nascer, é o meu corpo imolado por vós: perdão para todo o pecado.\n3. E ao partir do pão sua imagem se pareça, o amor nos une, e mais avança.\n4. Vou partir; deixo minha paz, convosco vai o meu amor.\n5. Irei ao Pai, sinto a vossa tristeza porém no céu, vos preparo outra mesa.\n6. De Deus virá o Espírito Santo, que vou mandar pra enxugar vosso pranto.",
                'autor'   => 'Waldeci Farias/Dom Navarro',
                'tom'     => 'D',
                'tema_id' => $comunhaoId,
                'ativo'   => true,
            ],
            [
                'numero'  => 213,
                'titulo'  => 'Cantarei ao Meu Senhor',
                'letra'   => "1. Cantarei ao meu Senhor e Deus, cantarei ao meu Senhor e Pai...\nDele hei de louvar todo dia aqui ou ali! (2x)\n2. Bendito Nome do Deus altíssimo, que me ensinou a rezar.\nCom Jesus repetirei, ao Pai a oração; bendito seja o Seu Nome!\n3. Onde eu for ou lhe gritarei de adoração, vou adorar ao meu Senhor.\n4. Estarei onde estiver a paz, ouvirei a voz do meu Senhor.\nRepetindo o que ele diz eu serei bem mais feliz se estiver ouvindo meu Senhor. (2x)\n5. Andarei seguro até na dor, meu caminho tem de ser amor.\n**Buscarei meu irmão e seremos povo do Senhor.**",
                'autor'   => 'Pe. Zezinho',
                'tom'     => 'D',
                'tema_id' => $finalId,
                'ativo'   => true,
            ],
            [
                'numero'  => 214,
                'titulo'  => 'São Muito Felizes',
                'letra'   => "**São muito felizes os que crêem mesmo sem ver,\nos que estão, Senhor Jesus, sob o Pão presente e vivo no meio de nós.\nEis o meu Corpo: tomai e comei. Eis o meu Sangue: tomai e bebei.**\n1. Só Tua vitória sobre a morte nos fez sorrir, e a alegria de saber\nO futuro de nossa vida é viver junto ao Pai.\n2. Com esta certeza de Teu Reino estar entre nós entregamos-te, Senhor, nossa vida e trabalhar na construção da paz.\n3. Juntos nas refeições nós queremos te agradecer, pois Tua vida em nossa vida nos faz, Senhor, ser sinais de um futuro feliz, unir o povo teu.",
                'autor'   => 'Ir. Lindbergh Pires',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 215,
                'titulo'  => 'Cristo Ressuscitou',
                'letra'   => "**Cristo ressuscitou, aleluia! Venceu a morte com o amor (2x) Aleluia!**\n1. Tendo vencido a morte, o Senhor ficará para sempre em nosso meio.\nPara manter viva a chama do amor que reside em cada cristão a caminho do Pai.\n2. O tendo vencido a morte, o Senhor nos abriu horizonte feliz,\npois nosso peregrinar pela face do mundo terá seu final na morada do Pai.",
                'autor'   => 'Ir. Lindbergh Pires',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 216,
                'titulo'  => 'Bendito Seja',
                'letra'   => "**Bendito seja o nosso Deus e nosso Pai (2x)\nque nos liberta com a sua paz (2x)**\n1. O Pai nos olha com imenso amor; por isso eu canto agora em seu louvor\n2. O Pai nos quer reino do amor, por isso eu canto agora em seu louvor",
                'autor'   => 'Pe. Zezinho',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 217,
                'titulo'  => 'Que Mais Podia Te Ter Feito',
                'letra'   => "Que mais podia eu ter feito, que mais podia eu te dar\nPlantei-te como vinha nova toda graciosa, nada igual\nAchei os mais escolhidos para te ampliar e te proteger\nO caminho no teu amor a te jogar certo, para o bem total\n**Esqueceste o amor e renegaste o Senhor, o mundo inteiro se esqueceu da luz e pregou seu Salvador na cruz**\nQue mais podia eu ter feito, que mais podia eu te dar\nDei pão da vida na nova aliança, de pedra ferida a sede apagou\nE fiz por amor teu povo escolhido os maiores feitos como ninguém viu\nE fiz por amor, te dei liberdade, o sol da verdade, onde nasce o amor",
                'autor'   => 'Pe. Irala',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 218,
                'titulo'  => 'És, Maria, a Virgem que Sabe Ouvir',
                'letra'   => "1. És, Maria, a Virgem que sabe acolher e ouvir com fé a santa palavra de Deus.\nCrescendo em graça e sabedoria, Ó Maria, tu és feliz!\n2. Respondendo o exemplo ao vosso chamado,\na nossa Igreja escolhe, acolhe a Palavra com fé,\neis a tua escolha, todos nós te saudamos: amém!",
                'autor'   => 'Waldeci Farias/Dom Navarro',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 219,
                'titulo'  => 'Ensina Teu Povo a Rezar',
                'letra'   => "Ensina teu povo a rezar, Maria, mãe de Jesus,\nUm dia o teu povo desperta e na certa vai ver a luz.\nMaria de Jesus Cristo, Maria de Deus, Maria mulher\nEnsina a teu povo o jeito de ser o que Deus quiser: (2x)\nMaria, Senhora nossa, mãe do povo, povo de Deus\nensina o jeito perfeito de sempre escutar teu Deus. (2x)",
                'autor'   => 'Pe. Zezinho',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 220,
                'titulo'  => 'O Senhor Necessitou de Braços',
                'letra'   => "**O Senhor necessitou de braços para ajudar a ceifar a messe.\nE eu ouvi seus apelos de amor, então respondi: Aqui estou, aqui estou.**\n1. Eu vim para dizer que eu quero te seguir.\n2. Eu quero viver com muito amor o que aprendi.\n3. Eu vim assumir a tua cruz e carregar...\n4. Eu vim para dizer que vou te acompanhar\nE com meus irmãos um mundo novo edificar...",
                'autor'   => 'Pe. Galvão',
                'tom'     => 'D',
                'tema_id' => $entradaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 221,
                'titulo'  => 'O Senhor me Chamou',
                'letra'   => "O Senhor me chamou a viver, a viver a alegria do amor\nFoi teu amor quem nos fez conhecer toda alegria, dá vida, Senhor.",
                'autor'   => 'Waldeci Farias/J. Braga',
                'tom'     => 'D',
                'tema_id' => $entradaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 222,
                'titulo'  => 'Senhor Que a Tua Palavra',
                'letra'   => "**Senhor, que a Tua Palavra transforme a nossa vida queremos caminhar com retidão na Tua luz**\n1. No Senhor está toda graça e salvação, n’Ele encontramos o amor, e o perdão.\n2. O Senhor é bom, é terno e compaixão, Seu amor nos chama a viver como irmãos.",
                'autor'   => 'Ir. Míria Kolling',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 223,
                'titulo'  => 'Eu Creio em Deus',
                'letra'   => "Deus é Pai, Deus é amor, Deus é esperança pra quem nele crê.\nConfio a construção do Reino de Paz ao homem que ama.\n**Eu creio em Deus, que por me amando iluminou,\nque a minha vida transformou. Feliz eu sou.\nEu creio em Deus, se posso crer, se posso amar,\nesta graça fez a minha vida ter valor. Feliz eu sou.**\n2. Jesus Cristo, é consolador, é amparo dos que choram.\nJesus Cristo, é a nossa força, e a vida dos homens, é ressurreição.\n3. Deus é amor, é esperança, é caridade, é vida, é paz. Deus é amor. Espírito Santo, destrói o que é mal, dá vida ao que é bom.",
                'autor'   => 'Pe. José Cândido',
                'tom'     => 'D',
                'tema_id' => $creioId,
                'ativo'   => true,
            ],
            [
                'numero'  => 224,
                'titulo'  => 'Minha Vida Tem Sentido',
                'letra'   => "Minha vida tem sentido, se eu venho aqui e faço o meu pedido, de não me esquecer de ti\n1. Meu amor como este pão que eu trago agora, que alguém plantou depois colheu e depois tornou-se salvação e deu mais vida e alimentou o povo meu.\n2. Eu te ofereço o vinho que agora é fruto, que alguém plantou depois colheu e depois encheu-se de carinho, se transformou em vida, e saciou o povo meu.",
                'autor'   => 'Pe. Zezinho',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 225,
                'titulo'  => 'Minha Alegria é Estar Perto de Deus',
                'letra'   => "**Minha alegria é estar perto de Deus (bis)**\n1. Por agora estaria sempre convosco, porque vós me tomastes pela mão.\n2. Porém agora cantarei a vossa glória, com um povo consagrado ao vosso amor.",
                'autor'   => 'Silvio Lúcio',
                'tom'     => 'D',
                'tema_id' => $entradaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 226,
                'titulo'  => 'Ó Tu Que És o Senhor da Vida',
                'letra'   => "Ó Tu, que és o Senhor da Vida, recebe em Tuas mãos a minha vida\n1. A Tua oferta nos dá coragem de nos doarmos para servir.\n2. No dia a dia, em Ti buscamos a força que nos sustenta.\n3. A Tua graça inunda a nossa história. Fiéis seremos o Teu amor.",
                'autor'   => 'Ir. Míria Kolling',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],
            [
                'numero'  => 227,
                'titulo'  => 'Perdão, Senhor',
                'letra'   => "**Perdão, Senhor, perdão por não ser santo.\nPerdão, Senhor, por ter pecado tanto.**\n1. A história é uma só da humanidade e minha.\nA queda sempre existe pra aquele que caminha.\nMas há um Salvador que vem ressuscitar aquele que da queda quiser se levantar.",
                'autor'   => 'Pe. Nereu',
                'tom'     => 'D',
                'tema_id' => $gloriaId,
                'ativo'   => true,
            ],

        ];

        foreach ($musicas as $musica) {
            DB::table('musicas')->insert([
                'numero'     => $musica['numero'],
                'titulo'     => $musica['titulo'],
                'letra'      => $musica['letra'],
                'autor'      => $musica['autor'],
                'tom'        => $musica['tom'],
                'tema_id'    => $musica['tema_id'],
                'ativo'      => $musica['ativo'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
